import openai

openai.api_key="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"
genres = ['Realism', 'Impressionism', 'Cubism', 'Abstract Expressionism',
          'Surrealism', 'Pop Art', 'Minimalism', 'Modern art']
openai.Model.list()

def generate_prompt(text):
        return f"Describe the following text as a one line short visual " \
               f"description of a scene:\n\"{text}\"\nDescription:"

def generate_response(text):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=generate_prompt(text),
        top_p=1,
    )
    return response.choices[0].text.strip()

def image_from_dalle(prompt):
    response = openai.Image.create(prompt=prompt,
                                   n=1,
                                size="1024x1024")
    return response['data'][0]['url']


def create_image(conf):
    """
    sends a confession to summarizion and returns a url of an image
    generated by dall e
    :param conf: original confession text in english
    :return: url of dall e image
    """
    prompt = generate_response(conf)
    return image_from_dalle(prompt)


    

# print('32632#. Again the pride parade and again my friends are trying to force me to go. \"It is your duty as a gay person to fight for your rights, and you have to show solidarity with your community.\" What are you talking about, what community? Just because I have a slightly different sexual orientation do I belong to the community? Hello, this is not my whole identity. I have more in common with straight people. So no thanks, I won\'t go to the parade, instead I\'ll go play basketball and maybe eat a hamburger afterwards. And yes, I\'ll add chips to the dish, thanks.')
# print(generate_response('32632#. Again the pride parade and again my friends are trying to force me to go. \"It is your duty as a gay person to fight for your rights, and you have to show solidarity with your community.\" What are you talking about, what community? Just because I have a slightly different sexual orientation do I belong to the community? Hello, this is not my whole identity. I have more in common with straight people. So no thanks, I won\'t go to the parade, instead I\'ll go play basketball and maybe eat a hamburger afterwards. And yes, I\'ll add chips to the dish, thanks.'))
if __name__ == '__main__':
    conf = '32632#. Again the pride parade and again my friends are trying to force me to go. \"It is your duty as a gay person to fight for your rights, and you have to show solidarity with your community.\" What are you talking about, what community? Just because I have a slightly different sexual orientation do I belong to the community? Hello, this is not my whole identity. I have more in common with straight people. So no thanks, I won\'t go to the parade, instead I\'ll go play basketball and maybe eat a hamburger afterwards. And yes, I\'ll add chips to the dish, thanks.'
    prompt = generate_response(conf)
    print(image_from_dalle(prompt))